<?php
$page_title = "پشتیبان‌گیری و بازیابی";
require_once '../includes/header.php';

// بررسی دسترسی ادمین
if ($_SESSION['role'] != 'admin') {
    header("Location: ../dashboard.php");
    exit;
}

// ایجاد پوشه backups اگر وجود ندارد
$backup_dir = "../backups/";
if (!file_exists($backup_dir)) {
    if (!mkdir($backup_dir, 0755, true)) {
        die("خطا در ایجاد پوشه پشتیبان");
    }
    // ایجاد فایل‌های امنیتی
    file_put_contents($backup_dir . "index.html", "<!DOCTYPE html><html><head><title>403 Forbidden</title></head><body><p>Directory access is forbidden.</p></body></html>");
    file_put_contents($backup_dir . ".htaccess", "Order deny,allow\nDeny from all");
}

$backup_success = $restore_success = $error = '';

// پشتیبان‌گیری
if (isset($_POST['backup'])) {
    $backup_file = $backup_dir . "backup_" . date("Y-m-d_H-i-s") . ".sql";
    
    try {
        // گرفتن لیست tables
        $tables = $db->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
        
        $backup_content = "";
        $backup_content .= "-- Backup generated by Inventory System\n";
        $backup_content .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
        $backup_content .= "-- Database: " . DB_NAME . "\n\n";
        
        foreach ($tables as $table) {
            // ساختار table
            $backup_content .= "--\n-- Table structure for table `$table`\n--\n";
            $create_table = $db->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_ASSOC);
            $backup_content .= $create_table['Create Table'] . ";\n\n";
            
            // داده‌های table
            $backup_content .= "--\n-- Dumping data for table `$table`\n--\n";
            
            $data = $db->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
            if (!empty($data)) {
                $columns = array_keys($data[0]);
                $backup_content .= "INSERT INTO `$table` (`" . implode('`, `', $columns) . "`) VALUES \n";
                
                $rows = [];
                foreach ($data as $row) {
                    $values = array_map(function($value) use ($db) {
                        if ($value === null) return 'NULL';
                        return $db->quote($value);
                    }, $row);
                    
                    $rows[] = "(" . implode(', ', $values) . ")";
                }
                
                $backup_content .= implode(",\n", $rows) . ";\n\n";
            }
        }
        
        // ذخیره فایل
        if (file_put_contents($backup_file, $backup_content)) {
            $backup_success = "پشتیبان‌گیری با موفقیت انجام شد. فایل: " . basename($backup_file);
            
            // حذف فایل‌های قدیمی (بیش از 30 روز)
            $files = glob($backup_dir . "backup_*.sql");
            $now = time();
            foreach ($files as $file) {
                if (is_file($file)) {
                    if ($now - filemtime($file) >= 30 * 24 * 60 * 60) { // 30 روز
                        unlink($file);
                    }
                }
            }
        } else {
            $error = "خطا در ذخیره فایل پشتیبان.";
        }
        
    } catch (Exception $e) {
        $error = "خطا در پشتیبان‌گیری: " . $e->getMessage();
    }
}

// بازیابی از فایل آپلود شده
if (isset($_POST['restore']) && !empty($_FILES['backup_file']['name'])) {
    $upload_file = $backup_dir . basename($_FILES['backup_file']['name']);
    
    // بررسی پسوند فایل
    $file_extension = pathinfo($_FILES['backup_file']['name'], PATHINFO_EXTENSION);
    if ($file_extension !== 'sql') {
        $error = "فقط فایل‌های با پسوند sql مجاز هستند.";
    } else {
        if (move_uploaded_file($_FILES['backup_file']['tmp_name'], $upload_file)) {
            $restore_success = "فایل آپلود شد. برای بازیابی از گزینه بازیابی در لیست فایل‌ها استفاده کنید.";
        } else {
            $error = "خطا در آپلود فایل.";
        }
    }
}

// بازیابی از فایل موجود
if (isset($_POST['restore_existing'])) {
    $restore_file = $_POST['restore_file'];
    
    if (file_exists($restore_file)) {
        try {
            $db->beginTransaction();
            
            // غیرفعال کردن foreign key checks
            $db->exec("SET FOREIGN_KEY_CHECKS = 0");
            
            // خواندن و اجرای فایل SQL
            $sql_content = file_get_contents($restore_file);
            $queries = array_filter(explode(';', $sql_content));
            
            foreach ($queries as $query) {
                if (trim($query) !== '') {
                    $db->exec($query);
                }
            }
            
            // فعال کردن مجدد foreign key checks
            $db->exec("SET FOREIGN_KEY_CHECKS = 1");
            
            $db->commit();
            $restore_success = "بازیابی با موفقیت انجام شد. سیستم نیاز به رفرش دارد.";
            
        } catch (Exception $e) {
            $db->rollBack();
            $error = "خطا در بازیابی: " . $e->getMessage();
        }
    } else {
        $error = "فایل پشتیبان وجود ندارد.";
    }
}

// حذف فایل پشتیبان
if (isset($_POST['delete_backup'])) {
    $delete_file = $_POST['delete_file'];
    
    if (file_exists($delete_file)) {
        if (unlink($delete_file)) {
            $backup_success = "فایل پشتیبان با موفقیت حذف شد.";
        } else {
            $error = "خطا در حذف فایل.";
        }
    } else {
        $error = "فایل پشتیبان وجود ندارد.";
    }
}

// دریافت لیست فایل‌های پشتیبان
$backup_files = [];
if (file_exists($backup_dir)) {
    $files = glob($backup_dir . "backup_*.sql");
    foreach ($files as $file) {
        if (is_file($file)) {
            $backup_files[] = [
                'name' => basename($file),
                'path' => $file,
                'size' => filesize($file),
                'date' => date("Y-m-d H:i:s", filemtime($file))
            ];
        }
    }
    
    // مرتب سازی بر اساس تاریخ (جدیدترین اول)
    usort($backup_files, function($a, $b) {
        return filemtime($b['path']) - filemtime($a['path']);
    });
}
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h2><i class="bi bi-cloud-arrow-down me-2"></i>مدیریت پشتیبان‌گیری</h2>
</div>

<?php if (!empty($error)): ?>
<div class="alert alert-danger alert-dismissible fade show">
    <i class="bi bi-exclamation-triangle me-2"></i><?php echo $error; ?>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
<?php endif; ?>

<?php if (!empty($backup_success)): ?>
<div class="alert alert-success alert-dismissible fade show">
    <i class="bi bi-check-circle me-2"></i><?php echo $backup_success; ?>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
<?php endif; ?>

<?php if (!empty($restore_success)): ?>
<div class="alert alert-success alert-dismissible fade show">
    <i class="bi bi-check-circle me-2"></i><?php echo $restore_success; ?>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
<?php endif; ?>

<div class="row">
    <div class="col-md-6">
        <div class="card mb-4">
            <div class="card-header bg-primary text-white">
                <h5 class="card-title mb-0">پشتیبان‌گیری از دیتابیس</h5>
            </div>
            <div class="card-body">
                <p class="card-text">با کلیک بر روی دکمه زیر، از کل دیتابیس سیستم پشتیبان گرفته می‌شود.</p>
                <form method="POST" action="">
                    <button type="submit" name="backup" class="btn btn-primary w-100">
                        <i class="bi bi-cloud-arrow-up me-2"></i>ایجاد پشتیبان
                    </button>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card mb-4">
            <div class="card-header bg-warning">
                <h5 class="card-title mb-0">بازیابی از پشتیبان</h5>
            </div>
            <div class="card-body">
                <p class="card-text">فایل پشتیبان (sql.) را برای آپلود انتخاب کنید.</p>
                <form method="POST" action="" enctype="multipart/form-data">
                    <div class="mb-3">
                        <input type="file" class="form-control" name="backup_file" accept=".sql" required>
                    </div>
                    <button type="submit" name="restore" class="btn btn-warning w-100">
                        <i class="bi bi-cloud-arrow-down me-2"></i>آپلود فایل
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-header bg-info text-white">
        <h5 class="card-title mb-0">فایل‌های پشتیبان موجود</h5>
    </div>
    <div class="card-body">
        <?php if (!empty($backup_files)): ?>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>نام فایل</th>
                        <th>حجم</th>
                        <th>تاریخ ایجاد</th>
                        <th>عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($backup_files as $file): ?>
                    <tr>
                        <td>
                            <code><?php echo $file['name']; ?></code>
                        </td>
                        <td><?php echo round($file['size'] / 1024, 2); ?> KB</td>
                        <td><?php echo $file['date']; ?></td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a href="<?php echo $file['path']; ?>" download class="btn btn-success">
                                    <i class="bi bi-download me-1"></i>دانلود
                                </a>
                                <form method="POST" action="" style="display:inline;">
                                    <input type="hidden" name="restore_file" value="<?php echo $file['path']; ?>">
                                    <button type="submit" name="restore_existing" class="btn btn-warning" 
                                            onclick="return confirm('⚠️ هشدار: تمام داده‌های فعلی جایگزین می‌شوند. آیا مطمئن هستید؟')">
                                        <i class="bi bi-arrow-clockwise me-1"></i>بازیابی
                                    </button>
                                </form>
                                <form method="POST" action="" style="display:inline;">
                                    <input type="hidden" name="delete_file" value="<?php echo $file['path']; ?>">
                                    <button type="submit" name="delete_backup" class="btn btn-danger" 
                                            onclick="return confirm('آیا از حذف این فایل اطمینان دارید؟')">
                                        <i class="bi bi-trash me-1"></i>حذف
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php else: ?>
        <div class="text-center py-4">
            <i class="bi bi-inbox display-1 text-muted"></i>
            <p class="text-muted mt-3">هیچ فایل پشتیبانی یافت نشد</p>
        </div>
        <?php endif; ?>
    </div>
</div>

<div class="alert alert-info mt-4">
    <h6><i class="bi bi-info-circle me-2"></i>راهنمای پشتیبان‌گیری</h6>
    <ul class="mb-0">
        <li>پشتیبان‌گیری به صورت خودکار هر 30 روز یکبار انجام شود</li>
        <li>فایل‌های پشتیبان قدیمی به صورت خودکار حذف می‌شوند</li>
        <li>قبل از بازیابی از سلامت فایل پشتیبان اطمینان حاصل کنید</li>
        <li>پس از بازیابی، سیستم نیاز به رفرش دارد</li>
    </ul>
</div>

<?php
require_once '../includes/footer.php';
?>